pipeline {
    agent {
        node {
            label 'agent-1'
        }
    }
    options {
        //timeout(time: 1, unit: 'HOURS')
        //disableConcurrentBuilds()
        ansiColor('xterm')
    }
    parameters {
        choice(name: 'action', choices: ['apply', 'destroy'], description: 'pick something')
    }
    //build
    stages {
        stage('init') {
            steps {
                sh """
                    cd 01-vpc
                    terraform init -reconfigure
                """
            }
        }
        stage('Plan') {
            steps {
                sh """
                    cd 01-vpc
                    terraform plan
                """
            }
        }
        stage('Deploy') {
            when {
                expression {
               params.action == 'apply' 
                }
            }
           input {
            message "Should we continue?"
            ok "Yes. we should."
            //
            //
            //
            //
           }
           steps {
            sh """
                    cd 01-vpc
                    terraform apply -auto-approve
                """
           }
        }
    }
    //psot build
      post { 
        always { 
            echo 'I will always say Hello again!'
        }
        failure{
            echo 'this runs when pipeline is failed, used generally to send some alerts'
        }
        success{
            echo 'I will say Hello, when pipeline is success'
        }
    }
}
